### ISSUE TITLE
Requirement hunter not listed in requirements

### ISSUE THREAD

**Issue by tweakimp** [Duroktar/Wolf#19] opened 2018-03-15 18:29 UTC
`pip install hunter` should be in the readme file

**Comment by Duroktar** [comment] 2018-03-15 21:00
Hunter should now be included, are you getting any errors or were you just noting the fact it's missing from the readme? If it's an error I'll take a look into it. Thanks!

**Comment by tweakimp** [comment] 2018-03-15 22:52
I just installed it again, when I save and run `wolf: Set the Wolf on the current file` it gives me this notification message:

> Wolf requires the hunter package. Install now or run 'pip install hunter --user' 

Could it be a problem that I am using the insider build?
<details>
- Version 1.22.0-insider
- Commit 509b8084d46b82ec5851447903cebd914e4535a5
- Datum 2018-03-15T09:31:27.063Z
- Shell 1.7.9
- Renderer 58.0.3029.110
- Node 7.9.0
- Architektur x64
</details>

**Comment by Duroktar** [comment] 2018-03-16 00:33
Awesome, thanks for posting the error! It's definitely because of the version you're running. We're up to v0.3.4 now, so if you upgrade to that then you'll likely not see the error anymore. Please let me know if that helps and thanks for trying Wolf!

**Comment by Duroktar** [comment] 2018-03-16 22:08
Hey, just reading through this again (I was pretty tired yesterday) and I think I read the error message wrong. So, if you are on the latest release (which I think you are) and it's giving that error, it's a bug I have to look into because Hunter _should_ be included with the extension now. Which I will do tonight :smiley:

**Comment by tweakimp** [comment] 2018-03-17 00:44
Yeah, I still got the error message^^

**Comment by Duroktar** [comment] 2018-03-17 00:48
Okay. So first of all I guess I'll add a note to the README like you suggested. Then I guess I'll be grabbing an insiders copy and seeing why it's not picking up the included package. Thanks again, I'll post here with results/progress.

**Comment by Duroktar** [comment] 2018-03-17 03:36
I wasn't able to reproduce the error on the insiders build, but I did get a note up on the README just in case. I managed to push a release as well (v0.3.4) which may clear it up (I was having issues with v0.3.2 on my mac so who knows, maybe it was related). 

I'll leave this issue open for visibility in case anyone else comes looking. And if you have any other suggestions feel free to shout.

**Comment by Duroktar** [comment] 2018-03-17 07:49
It is hardcoded in. But I left the other logic in just in case something like this happened. So it did work out in the end, they were presented with a solution to the error (yay! good me); but I still haven't managed to figure out why it didn't work on their build.

**Comment by Almenon** [comment] 2018-03-17 19:57
@tweakimp woah just realizes you can do dropdowns with markdown 0_o 

<details>
<summary>
Testing
</summary>
Tada!
</details

**Comment by Duroktar** [comment] 2020-11-26 02:21
Resolved in v0.4.0

**Closed by Duroktar** 2020-11-26 02:21 UTC
Labels: FAQ
