### ISSUE TITLE
Can't see the annotations

### ISSUE THREAD

**Issue by alankritjoshi** [Duroktar/Wolf#45] opened 2018-08-27 07:21 UTC
I know it's in the FAQ but I can't seem to get the annotations running. I tried setting `wolf.pythonPath`, ensuring the file is being saved and restarting Wolf. I am running VS Code on OSX.

**Comment by Duroktar** [comment] 2018-11-23 00:35
Terribly sorry for the late response. I fully intend to spend the winter paying more attention to this project (it is by no means abandoned ;P).

Did you manage to resolve the issue or can I still be of assistance? I run/develop Wolf on OSX so I can confirm that it _should_ work in that environment.

**Comment by igokul1973** [comment] 2020-01-07 13:28
Does not work for me either - same set-up with Mac OSX, VSCode v.1.41.1

**Comment by igokul1973** [comment] 2020-01-07 13:32
Actually, sorry, my bad (though it was not obvious) - I've set up the `wolf.pythonPath` and it is working now.

**Comment by Duroktar** [comment] 2020-01-07 13:40
@igokul1973 Glad you got it going :)

**Comment by igokul1973** [comment] 2020-01-07 14:11
Thanks for the great extension! Отправлено со смартфона Samsung Galaxy.
-------- Исходное сообщение --------От: traBpUkciP <notifications@github.com> Дата: 07.01.20  16:40  (GMT+03:00) Кому: Duroktar/Wolf <Wolf@noreply.github.com> Копия: "Igor K." <igk19@rambler.ru>, Mention <mention@noreply.github.com> Тема: Re: [Duroktar/Wolf] Can't see the annotations (#45) @igokul1973 Glad you got it going :)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Duroktar/Wolf/issues/45?email_source=notifications\u0026email_token=ABJTYQ6RHQ5XSCPALIZNN4TQ4SA4NA5CNFSM4FRVGWOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEII4MMY#issuecomment-571590195",
"url": "https://github.com/Duroktar/Wolf/issues/45?email_source=notifications\u0026email_token=ABJTYQ6RHQ5XSCPALIZNN4TQ4SA4NA5CNFSM4FRVGWOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEII4MMY#issuecomment-571590195",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Duroktar** [comment] 2020-11-26 02:24
Closing for now. Feel free to reopen if there's more questions.

**Closed by Duroktar** 2020-11-26 02:24 UTC
