### ISSUE TITLE
wolf does not handle accents properly

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#20] opened 2018-03-17 03:55 UTC
This is a bit of a low-blow (accents are _very_ annoying to handle) but the issue does need to be raised

f = 'é' #?

**should:** output é

**instead:** outputs  
> File "<string>", line 1

as an error

**Comment by Duroktar** [comment] 2018-03-17 04:13
Have you tried it without a macro? It actually works on my mac. I'm worried the bigger issue is macros seem to be broken in this latest release... I'm looking into the problem right now. I'm surprised it didn't show in the snapshot test. Sorry bout that, but thanks for pointing it out!

**Comment by Almenon** [comment] 2018-03-17 04:20
it works when not using a macro :)

**Comment by Duroktar** [comment] 2018-03-17 07:43
Fixed in v0.3.7! Feel free to re-open if the issue is not fully resolved. Thanks again, 🍻

**Closed by Duroktar** 2018-03-17 07:43 UTC
Labels: question

**Comment by Almenon** [comment] 2018-03-17 15:39
fix verified as working :)
