### ISSUE TITLE
wolf does not display unsaved files properly

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#10] opened 2018-03-06 08:00 UTC
Wolf runs upon save - this is standard functionality that we have already discussed.  However, when running wolf for the first time it should use whatever is in the doc, unsaved or not.  Otherwise the user might modify or create a file without saving and then be confused as to why wolf doesn't show any output.

1. Open a new python file and type in:

```python
x=1+1
x
```
2. Run wolf
3. Wolf does not show any output

**Another example:**
1. Open a python file with the following contents:
```python
x=1+1
x
```
2. Change to x=1+2
3. Run wolf: x shows up as 2 instead of 3
(it is using the code of the saved version rather than new one)

You can still have the run upon save feature, there just needs to be code that gets the 'dirty' document text upon start.

**Comment by Duroktar** [comment] 2018-03-06 21:46
Strangely, I could not reproduce this when I was demoing Wolf to some colleagues today (I only saw this issue as I was walking out the door this morning) but I'm going to try again tonight after supper, etc.. Thanks for reporting though, and I'll tag you later on with an update. Cheers

**Comment by Duroktar** [comment] 2018-03-10 06:44
Fixed in upcoming release.

**Comment by Duroktar** [comment] 2018-03-11 01:58
<img width="844" alt="savebeforemessage" src="https://user-images.githubusercontent.com/19689932/37248652-3498d7ee-24ae-11e8-97f6-b713c30c6b21.png">

**Comment by Duroktar** [comment] 2018-03-11 06:16
Closing.

**Comment by Almenon** [comment] 2018-03-17 04:36
This is mostly fixed, but there is still one failing case:

1. create new file
2. Run wolf first thing *without editing the file at all*
3. wolf does not display

**Comment by Duroktar** [comment] 2018-03-17 13:41
Hmm, this requires some investigation! Thanks for reporting, I'll re-open the issue.

**Comment by Duroktar** [comment] 2018-03-28 03:24
If you mean there is zero annotations when the file is empty (when it's brand new) then I think that's an acceptable state. As soon as I start typing it begins to update. Does it update for you or is it "frozen" at this point in your scenario? If it's freezing then I'll have to look into it, otherwise I think this issue is closeable.

**Comment by Almenon** [comment] 2018-03-28 05:16
Sorry, I could have described the issue a bit better.  After creating a new file and running wolf on it first thing annotations do not appear even when editing the file. AKA it is frozen.

The exact sequence of steps:
1. launch VSC
2. control-n to create new file
3. control-shift-p to bring up command prompt thingy
4. type in wolf, select wolf: Set the Wolf on the current file

![image](https://user-images.githubusercontent.com/13080965/38010034-fd5be8dc-320b-11e8-90aa-5fc6de01c4c5.png)


5. type in x = 1+1 and press enter
6. type in x
7. annotation does not appear

![image](https://user-images.githubusercontent.com/13080965/38010008-de91facc-320b-11e8-8200-9603990be2a6.png)

Tested on Windows, not sure on mac/linux.

And yeah, obviously no annotations is an acceptable state if it were an empty file :P

**Comment by Duroktar** [comment] 2018-04-29 16:04
Hmm. Okay, I'll take a look into this again. Thanks a bunch!

**Comment by Duroktar** [comment] 2020-11-26 02:21
Resolved in v0.4.0

**Closed by Duroktar** 2020-11-26 02:21 UTC
Labels: bug
