### ISSUE TITLE
wolf does not display when output is between variable assignments

### ISSUE THREAD

**Issue by Almenon** [Duroktar/Wolf#13] opened 2018-03-10 16:15 UTC
The following examples correctly display output:

```python
x = 1
x
```

```python
x = 1
x
x = 
```

The following examples do not work:

```python
x = 1
x
x = 5
```

```python
x = 1
x
y = 'a'
```

```python
x = 1
x
x = "foo"
```

**Comment by Almenon** [comment] 2018-03-10 16:22
Almost forgot to mention - win 10, python 3.5

**Comment by Duroktar** [comment] 2018-03-10 17:31
Confirmed. I'll have this fixed for 0.3.0. Thanks my friend!

**Comment by Duroktar** [comment] 2018-03-10 21:48
Fixed in v0.3.0 upcoming release.

**Comment by Almenon** [comment] 2018-03-11 01:34
I pulled latest but I am still not getting any output.

**Comment by Duroktar** [comment] 2018-03-11 01:41
You're correct, this one regressed. Thanks for catching that!

**Comment by Almenon** [comment] 2018-03-11 01:43
I feel like the QA at my work.... do devs always have this many bugs? XD

(no disrespect meant, AREPL isn't exactly bug-free either :P )

**Comment by Duroktar** [comment] 2018-03-11 01:56
Yeah, it's like this with most software I think :) If everything worked right away it wouldn't be called "development" anymore! And no disrespect taken; you're helping me out _a ton_, I really couldn't be more thankful 🥂

**Comment by Duroktar** [comment] 2018-03-11 06:15
![issue13_1](https://user-images.githubusercontent.com/19689932/37250385-2283bea8-24da-11e8-9c6a-012a6cf47ed5.PNG)

----

![issue13_2](https://user-images.githubusercontent.com/19689932/37250386-27a82bf8-24da-11e8-9d54-54824faf4315.PNG)

----

![issue13_3](https://user-images.githubusercontent.com/19689932/37250387-2c0379fa-24da-11e8-80d5-a0f36c12b118.PNG)

----

That looks like it did it. I patched a few other things as well and it's all live now. Enjoy!

Also tested on Windows.

**Closed** 2018-03-11 06:15 UTC
Labels: bug
